max_message_length = 80
max_mute_reason_length = 50
auto_moderation_enabled = true
auto_moderation_use_thread_pool = true
spectators_chat = false
fix_chat = false
dictionary_file = "dictionary_ru.json"