modLoader="javafml"
loaderVersion="[32,)"
license="${license}"
issueTrackerURL="https://github.com/vakiliner/ChatModerator/issues"

[[mods]]
modId="chatmoderator"
version="${version}"
displayName="ChatModerator"
description='''
Модерация игроков в чате
'''
authors="VAKiliner"
displayURL="https://github.com/vakiliner/ChatModerator"
updateJSONURL="https://raw.githubusercontent.com/vakiliner/ChatModerator/refs/heads/main/update.json"

[[dependencies.chatmoderator]]
	modId="forge"
	mandatory=true
	versionRange="[32.0.72,37)"